version: '3'

services:
  backend:
    container_name: backendNest
    restart: always
    depends_on:
      - postgresDb
    build:
      context: .
      dockerfile: ./Dockerfile.backend
    ports:
      - 3333:3333
  postgresDb:
    container_name: database
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: kahoot
